// Mock data for UNT Get Involved Application
import type { Club, Event } from "./types"

export const clubs: Club[] = [
  {
    id: "1",
    name: "Computer Science Club",
    description: "A community for CS students to learn, collaborate, and grow together through workshops, hackathons, and networking events.",
    category: "Academic",
    memberCount: 245,
    meetingSchedule: "Every Wednesday, 6:00 PM",
    location: "Discovery Park, Room B155",
    contactEmail: "csclub@unt.edu",
    tags: ["technology", "programming", "networking"],
  },
  {
    id: "2",
    name: "Mean Green Gaming",
    description: "UNT's premier gaming community featuring competitive esports teams and casual gaming nights.",
    category: "Recreation",
    memberCount: 380,
    meetingSchedule: "Every Friday, 7:00 PM",
    location: "Union, Room 314",
    contactEmail: "gaming@unt.edu",
    tags: ["gaming", "esports", "social"],
  },
  {
    id: "3",
    name: "Environmental Club",
    description: "Dedicated to promoting sustainability and environmental awareness on campus through education and action.",
    category: "Service",
    memberCount: 120,
    meetingSchedule: "Every Tuesday, 5:30 PM",
    location: "Environmental Science Building, Room 110",
    contactEmail: "envclub@unt.edu",
    tags: ["environment", "sustainability", "volunteer"],
  },
  {
    id: "4",
    name: "Dance Ensemble",
    description: "Express yourself through various dance styles including hip-hop, contemporary, and cultural dances.",
    category: "Arts",
    memberCount: 85,
    meetingSchedule: "Monday & Thursday, 6:00 PM",
    location: "Rec Center, Dance Studio A",
    contactEmail: "dance@unt.edu",
    tags: ["dance", "performance", "arts"],
  },
  {
    id: "5",
    name: "Pre-Med Society",
    description: "Supporting future healthcare professionals with MCAT prep, hospital volunteering, and medical school guidance.",
    category: "Academic",
    memberCount: 190,
    meetingSchedule: "Every Thursday, 5:00 PM",
    location: "Life Sciences Building, Room 220",
    contactEmail: "premed@unt.edu",
    tags: ["medicine", "healthcare", "academic"],
  },
  {
    id: "6",
    name: "International Student Association",
    description: "Celebrating cultural diversity and helping international students feel at home at UNT.",
    category: "Cultural",
    memberCount: 310,
    meetingSchedule: "Every Saturday, 3:00 PM",
    location: "Union, Syndicate",
    contactEmail: "isa@unt.edu",
    tags: ["cultural", "international", "community"],
  },
]

export const events: Event[] = [
  {
    id: "1",
    title: "Spring Hackathon 2025",
    description: "24-hour coding competition with prizes and mentorship from industry professionals.",
    date: new Date(2025, 2, 15),
    startTime: "9:00 AM",
    endTime: "9:00 AM (next day)",
    location: "Discovery Park",
    clubId: "1",
    clubName: "Computer Science Club",
    category: "Academic",
  },
  {
    id: "2",
    title: "Gaming Tournament Finals",
    description: "Competitive finals for Valorant, League of Legends, and Super Smash Bros.",
    date: new Date(2025, 2, 20),
    startTime: "6:00 PM",
    endTime: "11:00 PM",
    location: "Union Ballroom",
    clubId: "2",
    clubName: "Mean Green Gaming",
    category: "Recreation",
  },
  {
    id: "3",
    title: "Campus Cleanup Day",
    description: "Join us in beautifying the UNT campus! Supplies and refreshments provided.",
    date: new Date(2025, 2, 22),
    startTime: "10:00 AM",
    endTime: "2:00 PM",
    location: "Library Mall",
    clubId: "3",
    clubName: "Environmental Club",
    category: "Service",
  },
  {
    id: "4",
    title: "Spring Dance Showcase",
    description: "Annual performance featuring student choreography and guest performers.",
    date: new Date(2025, 3, 5),
    startTime: "7:00 PM",
    endTime: "9:30 PM",
    location: "Murchison Performing Arts Center",
    clubId: "4",
    clubName: "Dance Ensemble",
    category: "Arts",
  },
  {
    id: "5",
    title: "MCAT Study Session",
    description: "Group study session focusing on Biology and Chemistry sections.",
    date: new Date(2025, 2, 18),
    startTime: "4:00 PM",
    endTime: "7:00 PM",
    location: "Willis Library, Room 443",
    clubId: "5",
    clubName: "Pre-Med Society",
    category: "Academic",
  },
  {
    id: "6",
    title: "International Food Festival",
    description: "Taste dishes from around the world and enjoy cultural performances.",
    date: new Date(2025, 3, 12),
    startTime: "11:00 AM",
    endTime: "4:00 PM",
    location: "Union, Lyceum",
    clubId: "6",
    clubName: "International Student Association",
    category: "Cultural",
  },
  {
    id: "7",
    title: "Tech Talk: AI in Healthcare",
    description: "Industry speaker discussing the future of artificial intelligence in medicine.",
    date: new Date(2025, 2, 25),
    startTime: "5:30 PM",
    endTime: "7:00 PM",
    location: "Discovery Park, B155",
    clubId: "1",
    clubName: "Computer Science Club",
    category: "Academic",
  },
  {
    id: "8",
    title: "Earth Day Celebration",
    description: "Tree planting, educational booths, and sustainability workshops.",
    date: new Date(2025, 3, 22),
    startTime: "9:00 AM",
    endTime: "3:00 PM",
    location: "Apogee Stadium Grounds",
    clubId: "3",
    clubName: "Environmental Club",
    category: "Service",
  },
]

export const categories = [
  "All",
  "Academic",
  "Recreation",
  "Service",
  "Arts",
  "Cultural",
]
